image: node:latest # (1)

stages:
  - build
  - test

# cache:
#  paths:
#    - node_modules/ # (2)

install_dependencies:
  stage: build
  script:
    - rm -rf node_modules
    - npm install # (3)
  artifacts:
    paths:
      - node_modules/

testing:
  stage: test
  script: npm run test # (4)
